<?php

return array (
  'actors' => 'ممثلين',
  'air_day' => 'يوم البث',
  'aired' => 'بُثَّ',
  'airs' => 'يُبَثَّ',
  'ascending' => 'تصاعدي',
  'comments' => 'تعليقات',
  'country' => 'بلد',
  'descending' => 'تنازلي',
  'description' => 'وصف',
  'episode' => 'حلقة',
  'first_aired' => 'أول بث',
  'id' => 'معرَف',
  'imdb_rating' => 'تقدير IMDB',
  'latest_episode' => 'آخر حلقة',
  'name' => 'اسم',
  'network' => 'شبكة',
  'next_episode' => 'الحلقة القادمة',
  'no_actors_found' => 'لم يتم العثور على أي ممثل',
  'no_results' => 'لم يتم العثور على أي مسلسل',
  'none' => 'لا شيء',
  'order_by' => 'ترتيب ',
  'overview' => 'نظرة عامة',
  'previous_episode' => 'الحلقة السابقة',
  'releavance' => 'علاقة',
  'requests' => 'طلبات',
  'search' => 'بحث',
  'series' => 'مسلسل',
  'series_name' => 'اسم االمسلسل',
  'series_info' => 'معلومات االمسلسل',
  'show_info' => 'عرض المعلومات',
  'sort_by' => 'ترتيب حسب',
  'status' => 'الحالة',
  'year' => 'السنة',
  'similar' => 'مشابه',
  'season' => 'الموسم',
  'seasons' => 'مواسم',
  'torrents' => 'التورنتس',
  'updated' => 'محدَث',
  'rating' => 'تقييم',
  'site_rating' => 'تقييم الموقع',
  'fanart' => 'فن المعجبين',
);
