<?php

return array (
  'season' => 'الموسم',
  'episode' => 'حلقة',
  'episode_number' => 'رقم الحلقة',
  'episode_or_season' => 'الحلقة أو الموسم؟',
  'none_found' => 'لا يوجد تورنت',
  'search' => 'بحث',
  'season_number' => 'رقم الموسم',
  'size' => 'الحجم',
  'source' => 'أصل',
  'codec' => 'كوديك',
  'resolution' => 'أبعاد الفيديو',
  'origin' => 'الأصل',
  'series' => 'مسلسل',
  'series_name' => 'اسم المسلسل',
  'series_title' => 'عنوان المسلسل',
  'upload' => 
  array (
    'title' => 'العنوان',
    'release_name' => 'اسم الإصدار',
    'announce_url' => 'موقع النشر',
    'anonymous' => 'مجهول',
    'anonymous_info' => 'إجعل اسم شهرتك الخاص مجهولا في هذا التحميل',
    'episode_not_found' => 'الحلقة غير موجودة في قاعدة البيانات',
    'invalid_file' => 'ملف التورنت غير صالح',
    'rar_not_allowed' => 'ملفات RAR غير مسموخ بها في التورنتس الخاص بك',
    'season_not_found' => 'الموسم لم يتم العثور عليه في قاعدة البيانات',
    'series_not_found' => 'السلسلة لا توجد في قاعدة البيانات',
    'torrent_exists' => 'التورنت موجود في قاعدة البيانات',
  ),
  'container' => 'حاوية',
  'uploaded' => 'رُفِّعَ',
  'leechers' => 'محملون',
  'order_by' => 'الترتيب حسب',
  'seeders' => 'سيدرز',
  'series_banner' => 'راية',
  'series_id' => 'معرَف السلسة',
  'ascending' => 'تصاعدي',
  'created_at' => 'أنشئ في',
  'descending' => 'تنازلي',
  'snatched' => 'حمَل',
  'sort_by' => 'ترتيب حسب',
  'torrents' => 'تورنتس',
);
