<?php

return [
    'home'  => 'Hjem',
    'blog'  => 'Blogg',
    'actors'    => 'Skuespillere',
    'donate'  => 'Donèr',
    'feed'  => 'Strømmer',
    'forums'  => 'Forum',
    'forums_create'  => 'Ny tråd',
    'messages'  => 'Meldinger',
    'messages_create'  => 'Ny melding',
    'notifications'  => 'Notifikasjoner',
    'recommendations'  => 'Anbefalinger',
    'reports'  => 'Rapporter',
    'requests'  => 'Ønsker',
    'rules'  => 'Regler',
    'series'  => 'Serier',
    'snatchlist'  => 'Nedlastede torrenter',
    'staff'  => 'Stab',
    'staffpm'  => 'Stab melding',
    'staffpm_create'  => 'Send melding til stab',
    'torrents'  => 'Torrenter',
    'user'  => 'Bruker',
    'invite'  => 'Inviter',
    'user_edit'  => 'Rediger profil' ,
    'user_next_class'  => 'Neste klasse',
    'friends'  => 'Venner',
    'awards'  => 'Trofeér',
    'series_rating'  => 'Serierangering',
    'reports_new'  => 'Ny rapport',
    'torrents_upload' => 'Last opp torrent',
];
