<?php

return array (
  'actors' => 'Skuespillere',
  'air_day' => 'Sendedato',
  'aired' => 'Sendt',
  'airs' => 'Sendes',
  'ascending' => 'Stigende',
  'comments' => 'Kommentar',
  'country' => 'Land',
  'descending' => 'Synkende',
  'description' => 'Beskrivelse',
  'episode' => 'Episode',
  'first_aired' => 'Sendt første gang',
  'id' => 'Id',
  'imdb_rating' => 'Imdb poengsum',
  'latest_episode' => 'Nyeste episode',
  'name' => 'Navn',
  'network' => 'TV Kanal',
  'next_episode' => 'Neste episode',
  'no_actors_found' => 'Ingen skuespillere funnet',
  'no_results' => 'Ingen serier funnet',
  'none' => 'Ingen',
  'order_by' => 'Rekkefølge',
  'overview' => 'Oversikt',
  'previous_episode' => 'Forrige episode',
  'releavance' => 'Relevanse',
  'requests' => 'Ønsker',
  'search' => 'Søk',
  'season' => 'Sesong',
  'seasons' => 'Sesonger',
  'series' => 'Serie',
  'series_info' => 'Serie informasjon',
  'series_name' => 'Serienavn',
  'show_info' => 'Informasjon om serie',
  'similar' => 'Lignende',
  'sort_by' => 'Sorter etter',
  'status' => 'Status',
  'torrents' => 'Torrenter',
  'updated' => 'Oppdatert',
  'year' => 'År',
  'site_rating' => 'Siden\'s rangering',
  'fanart' => 'Fan kunst',
  'rating' => 'Rangering',
);
