<?php

return array (
  'codec' => 'Kodek',
  'container' => 'Konteiner',
  'episode' => 'Episode',
  'episode_number' => 'Episode nummer',
  'episode_or_season' => 'Episode eller sesong?',
  'none_found' => 'Ingen torrenter funnet',
  'origin' => 'Opprinnelse',
  'resolution' => 'Oppløsning',
  'search' => 'Søk',
  'season' => 'Sesong',
  'season_number' => 'Sesong nummer',
  'series' => 'Serie',
  'series_name' => 'Serienavn',
  'series_title' => 'Serietittel',
  'size' => 'Størrelse',
  'source' => 'Kilde',
  'upload' => 
  array (
    'announce_url' => 'Announce URL',
    'release_name' => 'Releasenavn',
    'title' => 'Tittel',
    'anonymous' => 'Anonym',
    'anonymous_info' => 'Setter kallenavnet ditt som anonym på denne opplastningen',
    'episode_not_found' => 'Episoden ble ikke funnet i databasen',
    'invalid_file' => 'Ugyldig torrentfil',
    'rar_not_allowed' => 'RAR-filer er ikke tillatt i torrenter',
    'season_not_found' => 'Sesongen ble ikke funnet i databasen',
    'series_not_found' => 'Serien ble ikke funnet i databasen',
    'torrent_exists' => 'Torrenten eksisterer allerede i databasen',
  ),
  'uploaded' => 'Lastet opp',
  'ascending' => 'Stigende',
  'descending' => 'Synkende',
  'order_by' => 'Sorter etter',
  'sort_by' => 'Sorter etter',
  'snatched' => 'Snatchet',
  'seeders' => 'Delere',
  'leechers' => 'Nedlastere',
  'created_at' => 'Ble lagd',
  'series_banner' => 'Banner',
  'series_id' => 'Serie ID',
  'torrents' => 'Torrenter',
);
