<?php

return array (
  'api_key' => 'API-nøkkel',
  'custom_title' => 'Egendefinert tittel',
  'email' => 'E-post',
  'enable_notifications' => 'Slå på notifikasjoner',
  'forum_signature' => 'Forum signatur',
  'irc_channels' => 'IRC kanaler',
  'profile_info' => 'Profilinformasjon',
  'profile_irc_channel' => 'IRC kanal',
  'profile_irc_join' => 'Åpne kanalen?',
  'profile_paranoia' => 'Innstillinger for paranoia',
  'profile_paranoia_became_friends_with' => 'Ble venn med',
  'profile_paranoia_becamefriendswith' => 'Ble venn med',
  'profile_paranoia_bonus' => 'Bonus',
  'profile_paranoia_download' => 'Last ned',
  'profile_paranoia_downloaded_torrents' => 'Nedlastede torrenter',
  'profile_paranoia_forums_posted_in' => 'Forum som er postet i',
  'profile_paranoia_last_seen' => 'Sist sett',
  'profile_paranoia_friends_list' => 'Venneliste',
  'profile_paranoia_option' => 'Valg',
  'profile_paranoia_show_hide' => 'Vis/skjul',
  'profile_paranoia_total_data' => 'Total mengde data',
  'profile_paranoia_upload' => 'Last opp',
  'profile_paranoia_uploaded_torrents' => 'Opplastede torrenter',
  'theme' => 'Tema',
  'profile_paranoia_walls_posted_on' => 'Vegger du har skrevet på',
  'push_service' => 'Push-tjeneste',
  'profile_paranoia_snatches' => 'Snatches',
  'locale' => 'Språk',
  'profile_paranoia_downloadedtorrents' => 'Nedlastede torrenter',
  'profile_paranoia_forum_posts' => 'Forumposter',
  'profile_paranoia_forumspostedin' => 'Forum som er postet i',
  'profile_paranoia_friend_of' => 'Venn av',
  'profile_paranoia_friends_added' => 'Venner lagt til',
  'profile_paranoia_friendslist' => 'Venneliste',
  'profile_paranoia_invitees' => 'Inviterte',
  'profile_paranoia_join_date' => 'Ble meldem',
  'profile_paranoia_leeching' => 'Laster ned',
  'profile_paranoia_mutual_friends' => 'Felles venner',
  'profile_paranoia_seeding' => 'Laster opp',
  'profile_paranoia_showhide' => 'Vis/skjul',
  'profile_paranoia_total_snatches' => 'Totalt snatchet',
  'profile_paranoia_totaldata' => 'Total mengde data',
  'profile_paranoia_uploadedtorrents' => 'Opplastede torrenter',
  'profile_paranoia_wall_posts' => 'Veggposter',
  'profile_paranoia_wallspostedon' => 'Vegger du har skrevet på',
  'avatar' => 'Avatar',
  'forum_show_signatures' => 'Forum
Vis signaturer',
);
