<?php

return [
    'home'  => 'Hjem',
    'blog'  => 'Blogg',
    'actors'    => 'Skuespillere',
    'donate'  => 'Donere',
    'feed'  => 'Strømmer',
    'forums'  => 'Forum',
    'forums_create'  => 'Ny tråd',
    'messages'  => 'Meldinger',
    'messages_create'  => 'Ny Melding',
    'notifications'  => 'Notifikasjoner',
    'recommendations'  => 'Anbefalinger',
    'reports'  => 'Rapporter',
    'requests'  => 'Ønsker',
    'rules'  => 'Regler',
    'series'  => 'Serier',
    'snatchlist'  => 'Snatch List',
    'staff'  => 'Stab',
    'staffpm'  => 'Stab PM',
    'staffpm_create'  => 'Ny Stab PM',
    'torrents'  => 'Torrenter',
    'user'  => 'Bruker',
    'invite'  => 'Inviter',
    'user_edit'  => 'Rediger Profil',
    'user_next_class'  => 'Neste brukerklasse',
    'friends'  => 'Venner',
    'awards'  => 'Premier',
    'series_rating'  => 'Serie rangering',
    'reports_new'  => 'Ny Rapport',
    'torrents_upload' => 'Last Opp Torrent',
];
