<?php

return [
    'home'  => 'Home',
    'blog'  => 'Blog',
    'actors'    => 'Actors',
    'donate'  => 'Donate',
    'feed'  => 'Feeds',
    'forums'  => 'Forums',
    'forums_create'  => 'New Thread',
    'messages'  => 'Messages',
    'messages_create'  => 'New Message',
    'notifications'  => 'Notifications',
    'recommendations'  => 'Recommendations',
    'reports'  => 'Reports',
    'requests'  => 'Requests',
    'request_create' => 'New Request',
    'rules'  => 'Rules',
    'series'  => 'Series',
    'snatchlist'  => 'Snatch List',
    'staff'  => 'Staff',
    'staffpm'  => 'Staff PM',
    'staffpm_create'  => 'New Staff PM',
    'torrents'  => 'Torrents',
    'user'  => 'User',
    'invite'  => 'Invite',
    'user_edit'  => 'Edit Profile',
    'user_next_class'  => 'Next Class',
    'friends'  => 'Friends',
    'awards'  => 'Awards',
    'series_rating'  => 'Series Ratings',
    'reports_new'  => 'New Report',
    'torrents_upload' => 'Upload Torrent',
    'wiki'          => 'Wiki',
];
