<?php

return array (
    'my_account' => 'My Account',
    'profile' => 'Profile',
    'messages' => 'Messages',
    'sign_out' => 'Sign Out',
    'blog'  => 'Blog',
    'donate'    => 'Donate',
    'feed' => 'Feed Generator',
    'forums' => 'Forums',
    'forums_edit_post' => 'Edit Post',
    'home' => 'Home',
    'messages' => 'Messages',
    'messages_create' => 'New Message',
    'notifications' => 'Notifications',
    'series_rating' => 'Series Ratings',
    'recommendations' => 'User Recommendations',
    'reports' => 'Reports',
    'report_create' => 'New Report',
    'requests' => 'Requests',
    'requests_create' => 'New Request',
    'rules' => 'Rules',
    'series' => 'Series',
    'snatchlist' => 'Snatch List',
    'staff' => 'Staff',
    'staffpm' => 'Staff PM',
    'staffpm_create' => 'New Staff PM',
    'torrents' => 'Torrents',
    'torrents_edit' => 'Edit Torrent',
    'torrents_upload' => 'Upload Torrent',
    'awards' => 'Awards',
    'friends' => 'Friends',
    'user_edit' => 'Edit Profile',
    'invite' => 'Invite',
    'wiki' => 'Wiki',
    'next_class' => 'Next Class',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
);
