<?php

return [
    'series_name' => 'Series Name',
    'search' => 'Search',
    'advanced_search' => 'Advanced Search',
    'resolution' => 'Resolution',
    'codec' => 'Codec',
    'container' => 'Container',
    'source' => 'Source',
    'origin' => 'Origin',
    'series' => 'Series',
    'size' => 'Size',
    'none_found' => 'No torrents found',
    'upload' => [
        'title' => 'Title',
        'announce_url' => 'Announce URL',
        'release_name' => 'Release Name',
        'anonymous' => 'Anonymous',
        'anonymous_info' => 'Marks your nickname as anonymous on this upload',
        'torrent_exists' => 'Torrent exists in the database',
        'episode_not_found' => 'Episode not found in database',
        'season_not_found' => 'Season not found in database',
        'series_not_found' => 'Series not found in database',
        'rar_not_allowed' => 'Archives (zip, RAR, etc) are not allowed in your torrents',
        'invalid_file' => 'Invalid torrent file',
    ],
    'episode_or_season' => 'Episode Or Season?',
    'episode' => 'Episode',
    'season' => 'Season',
    'season_number' => 'Season Number',
    'episode_number' => 'Episode Number',
    'series_title' => 'Series Title',
    'uploaded' => 'Uploaded',
    'sort_by' => 'Sort By',
    'created_at' => 'Created At',
    'snatched' => 'Snatched',
    'seeders' => 'Seeders',
    'leechers' => 'Leechers',
    'order_by' => 'Order By',
    'ascending' => 'Ascending',
    'descending' => 'Descending',
    'series_banner' => 'Banner',
    'series_id' => 'Series Id',
    'torrents' => 'Torrents',
    'mediainfo' => 'Mediainfo Log',
    'additional' => 'Additional Info'
];
