<?php

return [
    'torrents'               => 'Torrents',
    'requests'               => 'Anfragen',
    'home'                   => 'Home',
    'blog'                   => 'Blog',
    'forum'                  => 'Forum',
    'series'                 => 'Serien',
    'browse'                 => 'Browsen',
    'upload'                 => 'Hochladen',
    'support'                => 'Support',
    'wiki'                   => 'Wiki',
    'rules'                  => 'Regeln',
    'staff'                  => 'Belegschaft',
    'user'                   => 'Benutzer',
    'messages'               => 'Nachrichten',
    'admin'                  => 'Admin',
    'admin_dashboard'        => 'Dashboard',
    'snatchlist'             => 'Geschnappt',
    'invite'                 => 'Einladen',
    'reports'                => 'Meldungen',
    'donate'                 => 'Spenden',
    'staffpm'                => 'Belegschafts PM',
    'issues'                 => 'Probleme',
    'friends'                => 'Freunde',
    'rss'                    => 'RSS',
    'recommendations'        => 'Empfehlungen',
    'admin_staffpm'          => 'Belegschafts PM',
    'admin_users'            => 'Benutzer',
    'admin_users_advanced'   => 'Benutzer Erweitert',
    'admin_torrents'         => 'Torrents',
    'admin_issues'           => 'Probleme',
    'admin_groups'           => 'Gruppen',
    'admin_permissions'      => 'Berechtigungen',
    'admin_comments'         => 'Kommentare',
    'admin_reports'          => 'Meldungen',
    'admin_wiki'             => 'Wiki',
    'admin_rules'            => 'Regeln',
    'admin_blog'             => 'Blog',
    'admin_client_whitelist' => 'Whitelist',
    'admin_irc_channels'     => 'IRC Kanäle',
    'admin_series_mapping'   => 'Serienzuordnung',
    'admin_forums'           => 'Foren',
    'admin_forum_groups'     => 'Forumsgruppen',
];
