<?php

return array (
  'previous_episode' => 'Vorherige Folge',
  'season' => 'Staffel',
  'episode' => 'Folge',
  'aired' => 'Ausgestrahlt',
  'airs' => 'Wird Ausgestrahlt',
  'next_episode' => 'Nächste Folge',
  'torrents' => 'Torrents',
  'requests' => 'Anfragen',
  'comments' => 'Kommentare',
  'series_info' => 'Serieninformationen',
  'series_name' => 'Serienname',
  'year' => 'Jahr',
  'network' => 'TV Network',
  'status' => 'Status',
  'country' => 'Land',
  'sort_by' => 'Sortieren Nach',
  'releavance' => 'Relevanz',
  'id' => 'ID',
  'air_day' => 'Ausstrahlungstag',
  'imdb_rating' => 'iMDB Bewertung',
  'first_aired' => 'Zuerst Ausgestrahlt',
  'updated' => 'Aktualisiert',
  'order_by' => 'Reihenfolge',
  'ascending' => 'Steigend',
  'descending' => 'Fallend',
  'series' => 'Serien',
  'airs' => 'Wird Ausgestrahlt',
  'no_results' => 'Keine Serien Gefunden',
  'latest_episode' => 'Letzte Folge',
  'show_info' => 'Show-Info',
  'seasons' => 'Staffeln',
  'actors' => 'Schauspieler',
  'overview' => 'Übersicht',
  'name' => 'Name',
  'description' => 'Beschreibung',
  'no_actors_found' => 'Keine Schauspieler Gefunden',
  'none' => 'Keine',
  'search' => 'Suche',
  'advanced_search' => 'Erweiterte Suche',
  'similar' => 'Ähnliches',
  'site_rating' => 'Seitenbewertung',
  'rating' => 'Bewertung',
  'fanart' => 'Fankunst',
  'score' => 'Punktzahl',
);
