<?php

return array (
  'series_name' => 'Serienname',
  'search' => 'Suche',
  'advanced_search' => 'Erweiterte Suche',
  'resolution' => 'Auflösung',
  'codec' => 'Codec',
  'container' => 'Container',
  'source' => 'Quelle',
  'origin' => 'Ursprung',
  'series' => 'Serie',
  'size' => 'Größe',
  'none_found' => 'Keine Torrents gefunden',
  'upload' =>
  array (
    'title' => 'Titel',
    'announce_url' => 'Ankündigungs-URL',
    'release_name' => 'Releasename',
    'anonymous' => 'Anonym',
    'anonymous_info' => 'Markiert deinen Spitznamen als anonym für diesen Upload',
    'torrent_exists' => 'Torrent existiert in der Datenbank',
    'episode_not_found' => 'Folge nicht in der Datenbank gefunden',
    'season_not_found' => 'Staffel nicht in der Datenbank gefunden',
    'series_not_found' => 'Serie nicht in der Datenbank gefunden',
    'rar_not_allowed' => 'RARs nicht erlaubt in deinen Torrents',
    'invalid_file' => 'Ungültige Torrentdatei',
  ),
  'episode_or_season' => 'Folge Oder Staffel?',
  'episode' => 'Folge',
  'season' => 'Staffel',
  'season_number' => 'Staffelnummer',
  'episode_number' => 'Folgennummer',
  'series_title' => 'Serientitel',
  'uploaded' => 'Hochgeladen',
  'sort_by' => 'Sortiert Nach',
  'created_at' => 'Erstellt Am',
  'snatched' => 'Geschnappt',
  'seeders' => 'Seeder',
  'leechers' => 'Leecher',
  'order_by' => 'Reihenfolge',
  'ascending' => 'Steigend',
  'descending' => 'Fallend',
  'series_banner' => 'Banner',
  'series_id' => 'Serien-ID',
  'torrents' => 'Torrents',
);
