<?php

return [
    'home'  => '首页',
    'blog'  => '公告',
    'actors'    => '演员',
    'donate'  => '捐赠',
    'feed'  => '订阅',
    'forums'  => '论坛',
    'forums_create'  => '发表新主题',
    'messages'  => '短讯',
    'messages_create'  => '新建短讯',
    'notifications'  => '提醒',
    'recommendations'  => '推荐',
    'reports'  => '举报',
    'requests'  => '求种',
    'rules'  => '规则',
    'series'  => '剧集',
    'snatchlist'  => '完成种子',
    'staff'  => '管理组',
    'staffpm'  => '管理组短讯',
    'staffpm_create'  => '给管理组发短讯',
    'torrents'  => '种子',
    'user'  => '会员',
    'invite'  => '邀请',
    'user_edit'  => '个人设定',
    'user_next_class'  => '下一等级',
    'friends'  => '好友',
    'awards'  => '勋章',
    'series_rating'  => '剧集评分',
    'reports_new'  => '发起举报',
    'torrents_upload' => '上传种子',
    'wiki'          => '百科',
];
