<?php

return [
    'torrents'               => '种子',
    'requests'               => '求种',
    'home'                   => '主页',
    'blog'                   => '公告',
    'forum'                  => '论坛',
    'series'                 => '剧集',
    'browse'                 => '浏览',
    'upload'                 => '上传',
    'support'                => '帮助',
    'wiki'                   => '百科',
    'rules'                  => '规则',
    'staff'                  => '管理组',
    'user'                   => '用户',
    'messages'               => '短讯',
    'admin'                  => '管理员',
    'admin_dashboard'        => '控制面板',
    'snatchlist'             => '完成种子',
    'invite'                 => '邀请',
    'reports'                => '举报',
    'donate'                 => '捐赠',
    'staffpm'                => '管理组短讯',
    'issues'                 => '问题',
    'friends'                => '好友',
    'feeds'                  => '订阅',
    'recommendations'        => '推荐',
    'admin_staffpm'          => '管理组短讯',
    'admin_users'            => '用户',
    'admin_users_advanced'   => '更多用户信息',
    'admin_torrents'         => '种子',
    'admin_issues'           => '问题',
    'admin_groups'           => '组',
    'admin_permissions'      => '权限',
    'admin_comments'         => '评论',
    'admin_reports'          => '举报',
    'admin_wiki'             => '百科',
    'admin_rules'            => '规则',
    'admin_blog'             => '公告',
    'admin_client_whitelist' => '客户端白名单',
    'admin_irc_channels'     => 'IRC频道',
    'admin_series_mapping'   => 'Series Mapping',
    'admin_forums'           => '论坛',
    'admin_forum_groups'     => '论坛区',
    'awards'                 => '奖章',
];
