<?php

return [
    'series_name' => '剧集名称',
    'search' => '搜索',
    'advanced_search' => '高级搜索',
    'resolution' => '分辨率',
    'codec' => '编码',
    'container' => '格式',
    'source' => '片源',
    'origin' => '来自',
    'series' => '剧集',
    'size' => '大小',
    'none_found' => '没有找到种子',
    'upload' => [
        'title' => '标题',
        'announce_url' => 'Tracker地址',
        'release_name' => '种子标题',
        'anonymous' => '匿名',
        'anonymous_info' => '以匿名方式上传',
        'torrent_exists' => '种子已存在',
        'episode_not_found' => '该集在数据库中没有找到',
        'season_not_found' => '该季在数据库中没有找到',
        'series_not_found' => '该剧集在数据库中没有找到',
        'rar_not_allowed' => '压缩文件(zip, RAR, 等等)是不允许的',
        'invalid_file' => '种子文件不合法',
    ],
    'episode_or_season' => '单集还是一季的合集?',
    'episode' => '集',
    'season' => '季',
    'season_number' => '季数',
    'episode_number' => '集数',
    'series_title' => '剧集标题',
    'uploaded' => '上传',
    'sort_by' => '排序方法',
    'created_at' => '创建时间',
    'snatched' => '完成次数',
    'seeders' => '做种者',
    'leechers' => '下载者',
    'order_by' => '排序方法',
    'ascending' => '上升',
    'descending' => '下降',
    'series_banner' => '横幅',
    'series_id' => '剧集ID',
    'torrents' => '种子',
];
