<?php

    return [
        'torrents'               => 'Torrents',
        'requests'               => 'Solicitudes',
        'home'                   => 'Casa',
        'blog'                   => 'Blog',
        'forum'                  => 'Foro',
        'series'                 => 'Serie',
        'browse'                 => 'Explorar',
        'upload'                 => 'Subir',
        'support'                => 'Apoyo',
        'wiki'                   => 'Wiki',
        'rules'                  => 'Reglas',
        'staff'                  => 'Empleados',
        'user'                   => 'Usuario',
        'messages'               => 'Mensajes',
        'admin'                  => 'Administración',
        'admin_dashboard'        => 'Salpicadero',
        'snatchlist'             => 'Lista de Snatch',
        'invite'                 => 'Invitar',
        'reports'                => 'Informes',
        'donate'                 => 'Donar',
        'staffpm'                => 'MP al Empleados',
        'friends'                => 'Amigos',
        'feeds'                  => 'Canales',
        'recommendations'        => 'Recomendaciones',
        'admin_staffpm'          => 'MP al Empleados',
        'admin_users'            => 'Usuarios',
        'admin_users_advanced'   => 'Usuarios avanzada',
        'admin_torrents'         => 'Torrents',
        'admin_issues'           => 'Problemas',
        'admin_groups'           => 'Grupos',
        'admin_permissions'      => 'Permisos',
        'admin_comments'         => 'Comentarios',
        'admin_reports'          => 'Informes',
        'admin_wiki'             => 'Wiki',
        'admin_rules'            => 'Reglas',
        'admin_blog'             => 'Blog',
        'admin_client_whitelist' => 'Lista Blanca',
        'admin_irc_channels'     => 'Canales IRC',
        'admin_series_mapping'   => 'Mapeo Series',
        'admin_forums'           => 'Foro',
        'admin_forum_groups'     => 'Grupos Foro',
    ];
