<?php

return array (
  'previous_episode' => 'Anterior episodio',
  'season' => 'Temporada',
  'episode' => 'Episodio',
  'aired' => 'Transmitido',
  'airs' => 'Transmite',
  'next_episode' => 'Siguiente episodio',
  'torrents' => 'Torrents',
  'requests' => 'Solicitudes',
  'comments' => 'Comentarios',
  'series_info' => 'Información de la serie',
  'series_name' => 'Nombre de la serie',
  'year' => 'Año',
  'network' => 'Red',
  'status' => 'Estado',
  'country' => 'País',
  'sort_by' => 'Ordenar Por',
  'releavance' => 'Pertinencia',
  'id' => 'ID',
  'air_day' => 'Fecha de transmisión',
  'imdb_rating' => 'iMDB Clasificación',
  'first_aired' => 'Emitió por primera vez',
  'updated' => 'Actualizado',
  'order_by' => 'Orden',
  'ascending' => 'Asc',
  'descending' => 'Desc',
  'series' => 'Serie',
  'airs' => 'Transmite',
  'no_results' => 'No se encontró series',
  'latest_episode' => 'Último episodio',
  'show_info' => 'Mostrar información',
  'seasons' => 'Estaciones',
  'actors' => 'Actores',
  'overview' => 'Visión de conjunto',
  'name' => 'Nombre',
  'description' => 'Descripción',
  'no_actors_found' => 'No se han encontrado Actores',
  'none' => 'Ninguno',
  'search' => 'Buscar',
  'advanced_search' => 'Búsqueda Avanzada',
  'similar' => 'Similar',
  'site_rating' => 'Clasificación de sitio',
  'rating' => 'Clasificación',
  'fanart' => 'Arte de fan',
  'score' => 'Puntuación',
);