<?php

return array (
  'series_name' => 'Nombre de serie',
  'search' => 'Buscar',
  'advanced_search' => 'Búsqueda Avanzada',
  'resolution' => 'Resolución',
  'codec' => 'Codec',
  'container' => 'Contenedor',
  'source' => 'Fuente',
  'origin' => 'Origen',
  'series' => 'Serie',
  'size' => 'Tamaño',
  'none_found' => 'No se encontraron torrents',
  'upload' => 
  array (
    'title' => 'Título',
    'announce_url' => 'URL Anuncio',
    'release_name' => 'Nombre del estreno',
    'anonymous' => 'Anónimo',
    'anonymous_info' => 'Marca su apodo como anónimo en esta subida.',
    'torrent_exists' => 'Torrent existe en la base de datos',
    'episode_not_found' => 'Episodio no se encuentra en la base de datos',
    'season_not_found' => 'Temporada no se encuentra en la base de datos',
    'series_not_found' => 'Serie no se encuentra en la base de datos',
    'rar_not_allowed' => 'Archivos de RAR no están permitidos en sus torrents',
    'invalid_file' => 'Archivo torrent no válido',
  ),
  'episode_or_season' => 'Episodio O Temporada?',
  'episode' => 'Episodio',
  'season' => 'Temporada',
  'season_number' => 'Numero de Temporada',
  'episode_number' => 'Numero de Episodio',
  'series_title' => 'Título de Serie',
  'uploaded' => 'Subido',
  'sort_by' => 'Ordenar Por',
  'created_at' => 'Creado el',
  'snatched' => 'Arrebatado',
  'seeders' => 'Sembradoras',
  'leechers' => 'Leechers',
  'order_by' => 'Ordenar Por',
  'ascending' => 'Ascendente',
  'descending' => 'Descendente',
  'series_banner' => 'Bandera',
  'series_id' => 'ID de Serie',
  'torrents' => 'Torrents',
);