<?php

return array (
  'ascending' => 'Oplopend',
  'codec' => 'Codec',
  'container' => 'Container',
  'created_at' => 'Gemaakt op',
  'descending' => 'Aflopend',
  'episode' => 'Aflevering',
  'episode_number' => 'Aflevering nummer',
  'episode_or_season' => 'Aflevering of seizoen',
  'leechers' => 'Leechers',
  'none_found' => 'Geen torrents gevonden',
  'order_by' => 'Sorteer op',
  'origin' => 'Oorsprong',
  'resolution' => 'Resolutie',
  'search' => 'Zoek',
  'season' => 'Seizoen',
  'season_number' => 'Seizoen nummer',
  'seeders' => 'Seeders',
  'series' => 'Serie',
  'series_banner' => 'Banner',
  'series_id' => 'Serie-ID',
  'series_name' => 'Serie naam',
  'series_title' => 'Serie titel',
  'size' => 'Grootte',
  'sort_by' => 'Sorteer',
  'snatched' => 'Gesnatcht',
  'source' => 'Bron',
  'torrents' => 'Torrents',
  'upload' => 
  array (
    'announce_url' => 'Announce URL',
    'anonymous' => 'Anoniem',
    'anonymous_info' => 'Markeert jouw naam als Anoniem op deze upload',
    'episode_not_found' => 'Aflevering niet in de database gevonden',
    'invalid_file' => 'Ongeldig torrentbestand',
    'rar_not_allowed' => 'RAR-bestanden in torrents zijn niet toegestaan',
    'release_name' => 'Releasenaam',
    'season_not_found' => 'Seizoen niet in database gevonden',
    'series_not_found' => 'Serie niet in database gevonden',
    'title' => 'Titel',
    'torrent_exists' => 'Torrent bestaat al in de database',
  ),
  'uploaded' => 'Geüpload ',
);
