<?php

return array (
  'actors' => 'Atores',
  'air_day' => 'Dia de transmissão',
  'aired' => 'Transmitido',
  'airs' => 'Transmitido em',
  'ascending' => 'Ascendente',
  'comments' => 'Comentários',
  'country' => 'País',
  'descending' => 'Descendente',
  'description' => 'Descrição',
  'episode' => 'Episódio',
  'first_aired' => 'Transmitido primeiramente em',
  'id' => 'ID',
  'imdb_rating' => 'Nota IMDB',
  'latest_episode' => 'Último episódio',
  'name' => 'Nome',
  'network' => 'Rede',
  'next_episode' => 'Próximo episódio',
  'no_actors_found' => 'Nenhum ator encontrado',
  'no_results' => 'Nenhuma série encontrada',
  'none' => 'Nada',
  'order_by' => 'Ordenar',
  'overview' => 'Visão geral',
  'previous_episode' => 'Episódio passado',
  'releavance' => 'Relevância',
  'requests' => 'Pedidos',
  'search' => 'Buscar',
  'season' => 'Temporada',
  'seasons' => 'Temporada',
  'series' => 'Série',
  'series_info' => 'Info da série',
  'series_name' => 'Nome da série',
  'show_info' => 'Mostrar info',
  'sort_by' => 'Ordenar por',
  'status' => 'Status',
  'torrents' => 'Torrents',
  'updated' => 'Atualizado em',
  'year' => 'Ano',
  'fanart' => 'Arte de fãs',
  'rating' => 'Avaliação',
  'similar' => 'Similar',
  'site_rating' => 'Avaliação do site',
);
