<?php

return array (
  'codec' => 'Codec',
  'container' => 'Container',
  'episode' => 'Episódio',
  'episode_number' => 'Episódio nº',
  'episode_or_season' => 'Episódio ou temporada?',
  'none_found' => 'Nenhum torrent encontrado',
  'origin' => 'Origem',
  'resolution' => 'Resolução',
  'search' => 'Buscar',
  'season' => 'Temporada',
  'season_number' => 'Temporada nº',
  'series' => 'Séries',
  'series_name' => 'Nome do seriado',
  'series_title' => 'Título do seriado',
  'size' => 'Tamanho',
  'source' => 'Fonte',
  'upload' => 
  array (
    'announce_url' => 'Announce URL',
    'release_name' => 'Nome do release',
    'title' => 'Título',
    'torrent_exists' => 'O torrent já existe no banco de dados',
    'anonymous' => 'Anônimo',
    'anonymous_info' => 'Marque seu username como anônimo nesse upload',
    'episode_not_found' => 'Episódio não encontrado no banco de dados',
    'series_not_found' => 'Seriado não encontrado no banco de dados',
    'season_not_found' => 'Temporada não encontrada no banco de dados',
    'rar_not_allowed' => 'RARs não são permitidos no seu torrent',
    'invalid_file' => 'Arquivo torrent inválido',
  ),
  'uploaded' => 'Enviado em',
  'ascending' => 'Acendente',
  'created_at' => 'Criado em',
  'descending' => 'Decendente',
  'leechers' => 'Leechers',
  'order_by' => 'Ordenar por',
  'seeders' => 'Seeders',
  'series_banner' => 'Banner',
  'series_id' => 'ID do seriado',
  'snatched' => 'Baixado',
  'sort_by' => 'Ordenar por',
  'torrents' => 'Torrents',
);
