<?php

return [
    'home'  => '首頁',
    'blog'  => '公告',
    'actors'    => '演員',
    'donate'  => '捐贈',
    'feed'  => '訂閱',
    'forums'  => '論壇',
    'forums_create'  => '新主題',
    'messages'  => '短訊',
    'messages_create'  => '新短訊',
    'notifications'  => '提醒',
    'recommendations'  => '推薦',
    'reports'  => '舉報',
    'requests'  => '求種',
    'rules'  => '規則',
    'series'  => '劇集',
    'snatchlist'  => '完成種子',
    'staff'  => '管理組',
    'staffpm'  => '管理組短訊',
    'staffpm_create'  => '給管理組發短訊',
    'torrents'  => '種子',
    'user'  => '會員',
    'invite'  => '邀請',
    'user_edit'  => '個人設定',
    'user_next_class'  => '下一個用戶等級',
    'friends'  => '好友',
    'awards'  => '獎章',
    'series_rating'  => '劇集評分',
    'reports_new'  => '新舉報',
    'torrents_upload' => '上傳種子',
];
