<?php

return [
    'torrents' => '種子',
    'requests' => '求種',
    'home' => '首頁',
    'blog' => '公告',
    'forum' => '論壇',
    'series' => '劇集',
    'browse' => '瀏覽',
    'upload' => '上傳',
    'support' => '幫助',
    'wiki' => '百科',
    'rules' => '規則',
    'staff' => '管理組',
    'user' => '會員',
    'messages' => '短訊',
    'admin' => '管理員',
    'admin_dashboard' => '控制面板',
    'snatchlist' => '完成種子',
    'invite' => '邀請',
    'reports' => '舉報',
    'donate' => '捐贈',
    'staffpm' => '管理組短訊',
    'issues' => '問題',
    'friends' => '好友',
    'feeds' => '訂閱',
    'recommendations' => '推薦',
    'admin_staffpm' => '管理組短訊',
    'admin_users' => '用戶',
    'admin_users_advanced' => '更多用戶信息',
    'admin_torrents' => '種子',
    'admin_issues' => '問題',
    'admin_groups' => '組',
    'admin_permissions' => '權限',
    'admin_comments' => '評論',
    'admin_reports' => '舉報',
    'admin_wiki' => '百科',
    'admin_rules' => '規則',
    'admin_blog' => '公告',
    'admin_client_whitelist' => '客戶端白名單',
    'admin_irc_channels' => 'IRC頻道',
    'admin_series_mapping' => 'Series Mapping',
    'admin_forums' => '論壇',
    'admin_forum_groups' => '論壇區',
    'awards' => '獎章',
];
