<?php

return [
    'series_name' => '劇集名稱',
    'search' => '搜索',
    'advanced_search' => '高級搜索',
    'resolution' => '分辨率',
    'codec' => '編碼',
    'container' => '格式',
    'source' => '片源',
    'origin' => '來自',
    'series' => '劇集',
    'size' => '大小',
    'none_found' => '沒有找到種子',
    'upload' => [
        'title' => '標題',
        'announce_url' => 'Tracker地址',
        'release_name' => '種子標題',
        'anonymous' => '匿名',
        'anonymous_info' => '以匿名方式上傳',
        'torrent_exists' => '種子已存在',
        'episode_not_found' => '該集在數據庫中沒有找到',
        'season_not_found' => '該季在數據庫中沒有找到',
        'series_not_found' => '該劇集在數據庫中沒有找到',
        'rar_not_allowed' => '壓縮文件(zip, RAR, 等等)是不允許的',
        'invalid_file' => '種子文件不合法',
    ],
    'episode_or_season' => '單集還是整季?',
    'episode' => '集',
    'season' => '季',
    'season_number' => '季數',
    'episode_number' => '集數',
    'series_title' => '劇集標題',
    'uploaded' => '上傳',
    'sort_by' => '排序方法',
    'created_at' => '創建時間',
    'snatched' => '完成次數',
    'seeders' => '做種者',
    'leechers' => '下載者',
    'order_by' => '排序方法',
    'ascending' => '上升',
    'descending' => '下降',
    'series_banner' => '橫幅',
    'series_id' => '劇集ID',
    'torrents' => '種子',
];
