<?php

return [
    'home'  => 'Accueil',
    'blog'  => 'Blog',
    'actors'    => 'Acteurs',
    'donate'  => 'Faire un don',
    'feed'  => 'Flux RSS',
    'forums'  => 'Forums',
    'forums_create'  => 'Nouveau sujet',
    'messages'  => 'Messages',
    'messages_create'  => 'Nouveau message',
    'notifications'  => 'Notifications',
    'recommendations'  => 'Recommendations',
    'reports'  => 'Rapports',
    'requests'  => 'Requêtes',
    'request_create' => 'Nouvelle requête',
    'rules'  => 'Règles',
    'series'  => 'Séries',
    'snatchlist'  => 'Torrents complétés',
    'staff'  => 'Staff',
    'staffpm'  => 'Staff : Messages privés',
    'staffpm_create'  => 'Staff : Nouveau message privé',
    'torrents'  => 'Torrents',
    'user'  => 'Utilisateur',
    'invite'  => 'Invitation',
    'user_edit'  => 'Modification du profil',
    'user_next_class'  => 'Prochain rang',
    'friends'  => 'Amis',
    'awards'  => 'Récompenses',
    'series_rating'  => 'Évalutation des séries',
    'reports_new'  => 'Nouveau rapport',
    'torrents_upload' => 'Partager un torrent',
    'wiki'          => 'Wiki',
];
