<?php

return array (
    'my_account' => 'Mon compte',
    'profile' => 'Profil',
    'messages' => 'Messages',
    'sign_out' => 'Se déconnecter',
    'blog'  => 'Blog',
    'donate'    => 'Faire un don',
    'feed' => 'Activité',
    'forums' => 'Forums',
    'forums_edit_post' => 'Modifier le message',
    'home' => 'Accueil',
    'messages' => 'Messages',
    'messages_create' => 'Nouveau message',
    'notifications' => 'Notifications',
    'series_rating' => 'Évalutation des séries',
    'recommendations' => 'Recommandations des utilisateurs',
    'reports' => 'Rapports',
    'report_create' => 'Nouveau rapport',
    'requests' => 'Requêtes',
    'requests_create' => 'Nouvelle requête',
    'rules' => 'Règles',
    'series' => 'Séries',
    'snatchlist' => 'Torrents complétés',
    'staff' => 'Staff',
    'staffpm' => 'Staff : Messages privés',
    'staffpm_create' => 'Staff : Nouveau message privé',
    'torrents' => 'Torrents',
    'torrents_edit' => 'Modifier le torrent',
    'torrents_upload' => 'Upload Torrent',
    'awards' => 'Récompenses',
    'friends' => 'Mes amis',
    'user_edit' => 'Modifier mon profil',
    'invite' => 'Inviter un utilisateur',
    'wiki' => 'Wiki',
    'next_class' => 'Prochain rang',
);
