<?php

return array (
  'actors' => 'Acteurs',
  'air_day' => 'Jour de diffusion',
  'aired' => 'Diffusé',
  'airs' => 'Diffuse',
  'ascending' => 'Ascendant',
  'comments' => 'Commentaires',
  'country' => 'Pays',
  'descending' => 'Descendant',
  'description' => 'Description',
  'episode' => 'Épisode',
  'first_aired' => 'Première diffusion',
  'id' => 'ID',
  'imdb_rating' => 'Évaluation IMDb',
  'latest_episode' => 'Dernier épisode',
  'name' => 'Nom',
  'network' => 'Réseau',
  'next_episode' => 'Prochain épisode',
  'no_actors_found' => 'Aucun acteurs trouvés',
  'no_results' => 'Aucune série trouvé',
  'none' => 'Aucun',
  'order_by' => 'Ordre',
  'overview' => 'Vue d\'ensemble',
  'previous_episode' => 'Épisode précédent',
  'releavance' => 'Pertinence',
  'requests' => 'Requêtes',
  'search' => 'Recherche',
  'season' => 'Saison',
  'seasons' => 'Saisons',
  'series' => 'Série',
  'series_info' => 'Infos de la série',
  'series_name' => 'Nom de la série',
  'show_info' => 'Afficher les infos',
  'similar' => 'Similaire',
  'sort_by' => 'Trier par',
  'status' => 'Statut',
  'torrents' => 'Torrents',
  'updated' => 'Mis à jour',
  'year' => 'Année',
  'rating' => 'Évaluation',
  'site_rating' => 'Évaluation de site',
  'fanart' => 'Art d\'admirateur',
);
