<?php

return [
    'series_name' => 'Nom de la série',
    'search' => 'Recherche',
    'advanced_search' => 'Recherche avancée',
    'resolution' => 'Résolution',
    'codec' => 'Codec',
    'container' => 'Conteneur',
    'source' => 'Source',
    'origin' => 'Origine',
    'series' => 'Série',
    'size' => 'Taille',
    'none_found' => 'Aucun torrent trouvé',
    'upload' => [
        'title' => 'Titre',
        'announce_url' => 'URL d\'annonce',
        'release_name' => 'Nom de parution',
        'anonymous' => 'Anonyme',
        'anonymous_info' => 'Masquer votre identité pour cet upload',
        'torrent_exists' => 'Le torrent existe déjà dans la base de données',
        'episode_not_found' => 'Épisode introuvable dans la base de données',
        'season_not_found' => 'Saison introuvable dans la base de données',
        'series_not_found' => 'La série ne se trouve pas dans la base de données',
        'rar_not_allowed' => 'Fichiers RAR non autorisés dans vos torrents',
        'invalid_file' => 'Fichier torrent invalide',
    ],
    'episode_or_season' => 'Épisode ou saison ?',
    'episode' => 'Épisode',
    'season' => 'Saison',
    'season_number' => 'Numéro de de Saison',
    'episode_number' => 'Numéro de l\'épisode',
    'series_title' => 'Titre de la série',
    'uploaded' => 'Posté',
    'sort_by' => 'Trier par',
    'created_at' => 'Créé le',
    'snatched' => 'Complétés',
    'seeders' => 'Seeders',
    'leechers' => 'Leechers',
    'order_by' => 'Trier par',
    'ascending' => 'Ascendant',
    'descending' => 'Descendant',
    'series_banner' => 'Bannière',
    'series_id' => 'ID de la série',
    'torrents' => 'Torrents',
    'mediainfo' => 'Info sur le media',
    'additional' => 'Info complémentaires',
];
