<?php

return array (
  'codec' => 'Codec',
  'container' => 'Conteneur',
  'episode' => 'Épisode',
  'episode_number' => 'Numéro de l\'épisode',
  'episode_or_season' => 'Épisode ou saison?',
  'none_found' => 'Aucun torrent trouvé',
  'origin' => 'Origine',
  'resolution' => 'Résolution',
  'search' => 'Recherche',
  'season' => 'Saison',
  'season_number' => 'Numéro de de Saison',
  'series' => 'Série',
  'series_name' => 'Nom de la série',
  'series_title' => 'Titre de la série',
  'size' => 'Taille',
  'source' => 'Source',
  'upload' => 
  array (
    'announce_url' => 'L\'URL d\'annonce',
    'release_name' => 'Nom de parution',
    'title' => 'Titre',
    'anonymous' => 'Anonyme',
    'anonymous_info' => 'Marquer votre nom comme anonyme sur ce chargement.',
    'season_not_found' => 'Saison introuvable dans la base de données',
    'episode_not_found' => 'Épisode introuvable dans la base de données',
    'invalid_file' => 'Fichier torrent invalide',
    'rar_not_allowed' => 'Fichiers RAR non autorisés dans vos torrents',
    'series_not_found' => 'La série ne se trouve pas dans la base de données',
    'torrent_exists' => 'Le torrent existe dans la base de données',
  ),
  'uploaded' => 'Postés',
  'leechers' => 'Leechers',
  'order_by' => 'Trier par',
  'seeders' => 'Seeders',
  'series_banner' => 'Bannière',
  'series_id' => 'ID de série',
  'ascending' => 'Ascendant',
  'created_at' => 'Créé à',
  'descending' => 'Descendant',
  'snatched' => 'Complétés',
  'sort_by' => 'Trier Par',
  'torrents' => 'Torrents',
);
