<?php

    return [
        'torrents'               => 'Torrents',
        'requests'               => 'Исканията',
        'home'                   => 'у дома',
        'blog'                   => 'Блог',
        'forum'                  => 'форум',
        'series'                 => 'серия',
        'browse'                 => 'паса',
        'upload'                 => 'Качи',
        'support'                => 'подкрепа',
        'wiki'                   => 'Wiki',
        'rules'                  => 'правилник',
        'staff'                  => 'персонал',
        'user'                   => 'потребител',
        'messages'               => 'Съобщения',
        'admin'                  => 'администрация',
        'admin_dashboard'        => 'табло',
        'snatchlist'             => 'Snatchlist',
        'invite'                 => 'каня',
        'reports'                => 'Доклади',
        'donate'                 => 'Дарете',
        'staffpm'                => 'Лично съобщение Жезъла',
        'friends'                => 'Приятели',
        'feeds'                  => 'Каналы',
        'recommendations'        => 'Препоръки',
        'admin_staffpm'          => 'Лично съобщение Жезъла',
        'admin_users'            => 'Потребители',
        'admin_users_advanced'   => 'Потребители — напреднал',
        'admin_torrents'         => 'Torrents',
        'admin_issues'           => 'въпроси',
        'admin_groups'           => 'Групи',
        'admin_permissions'      => 'разрешения',
        'admin_comments'         => 'Коментари',
        'admin_reports'          => 'Доклади',
        'admin_wiki'             => 'Wiki',
        'admin_rules'            => 'правилник',
        'admin_blog'             => 'Блог',
        'admin_client_whitelist' => 'Бял списък',
        'admin_irc_channels'     => 'IRC канали',
        'admin_series_mapping'   => 'серия картографиране',
        'admin_forums'           => 'Форуми',
        'admin_forum_groups'     => 'Форум Групи',
    ];
