<?php

return array (
  'previous_episode' => 'предишния епизод',
  'season' => 'сезон',
  'episode' => 'епизод',
  'aired' => 'Излъчва',
  'airs' => 'Излъчва',
  'next_episode' => 'Следващ епизод',
  'torrents' => 'Torrents',
  'requests' => 'Исканията',
  'comments' => 'Коментари',
  'series_info' => 'серия инфо',
  'series_name' => 'име на серия',
  'year' => 'година',
  'network' => 'мрежа',
  'status' => 'Статус',
  'country' => 'страна',
  'sort_by' => 'сортиране по',
  'releavance' => 'уместност',
  'id' => 'ID',
  'air_day' => 'въздушния ден',
  'imdb_rating' => 'iMDB оценка',
  'first_aired' => 'Премиера',
  'updated' => 'Обновено',
  'order_by' => 'Поръчка',
  'ascending' => 'възходящ',
  'descending' => 'Низходящо',
  'series' => 'серия',
  'airs' => 'излъчва',
  'no_results' => 'Не серия намерени',
  'latest_episode' => 'последния епизод',
  'show_info' => 'Покажи инф',
  'seasons' => 'сезони',
  'actors' => 'Актьори',
  'overview' => 'Преглед',
  'name' => 'име',
  'description' => 'описание',
  'no_actors_found' => 'Няма намерени актьори',
  'none' => 'никой',
  'search' => 'търсене',
  'advanced_search' => 'Разширено Търсене',
  'similar' => 'сходен',
  'site_rating' => 'Рейтинг на сайта',
  'rating' => 'оценка',
  'fanart' => 'фен арт',
  'score' => 'резултат',
);